- name: Copy, edit and delete a file
  hosts: ansibletest02
  tasks:
   - name: copy file basvaraj.txt
     ansible.builtin.copy:
      src: /tmp/basvaraj.txt
      dest: /tmp
      mod: '664'
     delegate_to: localhost

   - name: add some data the file basvaraj.txt
     ansible.builtin.lineinfile:
      path: /tmp/basvaraj.txt
      line: 'updating the file with some text to test'



   - name: deleting the basvaraj.txt file from test02
     ansible.builtin.file:
      path: /tmp/basvraj.txt
      state: absent

